---
# tasks file for vireo4.newdbV4

- name: install prerequisites
  yum: name={{ item }} state=latest
  with_items:
    - python-psycopg2
  tags:
    - packages

- name: stop vireo4
  service:
    name: vireo4
    enabled: yes
    state: stopped
  become: yes

- name: create backup of v4 database
  shell: "pg_dump -U postgres {{vireo_db4_name[current_site]}} > ~/{{ vireo_db4_name[current_site]}}_clone.sql"
  become: yes
  become_user: postgres
  ignore_errors: yes

- name: drop v4 new database
  postgresql_db:
    name: "{{vireo_db4_name_new[current_site]}}"
    state: absent
    owner: "{{ vireo_db_user[current_site] }}"
  become: yes
  become_user: postgres
  ignore_errors: yes

- name: create v4 new database
  postgresql_db:
    name: "{{vireo_db4_name_new[current_site]}}"
    state: present
    owner: "{{ vireo_db_user[current_site] }}"
  become: yes
  become_user: postgres

- name: build vireo4 new database from vireo4 dump
  postgresql_db:
    name: "{{ vireo_db4_name_new[current_site] }}"
    state: restore
    target: "~/{{ vireo_db4_name[current_site] }}_clone.sql"
  become: yes
  become_user: postgres

- name: grant v4 privileges to db_user
  postgresql_privs:
    db: "{{ vireo_db4_name_new[current_site] }}"
    role: "{{ vireo_db_user[current_site] }}"
    objs: ALL_IN_SCHEMA
    privs: SELECT,INSERT,UPDATE,DELETE
  become: yes
  become_user: postgres

- name: drop v4 direct database
  postgresql_db:
    name: "{{vireo_db4_name_direct[current_site]}}"
    state: absent
    owner: "{{ vireo_db_user[current_site] }}"
  become: yes
  become_user: postgres
  ignore_errors: yes

- name: create v4 direct database
  postgresql_db:
    name: "{{vireo_db4_name_direct[current_site]}}"
    state: present
    owner: "{{ vireo_db_user[current_site] }}"
  become: yes
  become_user: postgres

- name: build vireo4 direct database from vireo4 dump
  postgresql_db:
    name: "{{ vireo_db4_name_direct[current_site] }}"
    state: restore
    target: "~/{{ vireo_db4_name[current_site] }}_clone.sql"
  become: yes
  become_user: postgres

- name: grant v4 privileges to db_user
  postgresql_privs:
    db: "{{ vireo_db4_name_direct[current_site] }}"
    role: "{{ vireo_db_user[current_site] }}"
    objs: ALL_IN_SCHEMA
    privs: SELECT,INSERT,UPDATE,DELETE
  become: yes
  become_user: postgres

- name: start vireo4
  service:
    name: vireo4
    enabled: yes
    state: started
  become: yes


