---

- name: copy sql commands
  copy:
    src: "{{ item }}"
    dest: "/var/lib/pgsql/"
    owner: postgres
  with_fileglob: "files/*"
  become_user: postgres
  become: true

- name: run sql commands alter_nsfg
  shell: "psql -U postgres {{ vireo_db4_name[current_site] }} < /var/lib/pgsql/alter_nsfg.sql"
  become_user: postgres
  become: true

- name: run sql commands graduationDate 1
  shell: "psql -U postgres {{ vireo_db4_name[current_site] }} < /var/lib/pgsql/graduationDate_migrate_validators_1.sql"
  become_user: postgres
  become: true

- name: run sql commands graduationDate 2
  shell: "psql -U postgres {{ vireo_db4_name[current_site] }} < /var/lib/pgsql/graduationDate_migrate_baddata_2.sql"
  become_user: postgres
  become: true

- name: run sql commands graduationDate 3
  shell: "psql -U postgres {{ vireo_db4_name[current_site] }} < /var/lib/pgsql/graduationDate_migrate_gradsem_3.sql"
  become_user: postgres
  become: true

- name: run sql commands graduationDate 4
  shell: "psql -U postgres {{ vireo_db4_name[current_site] }} < /var/lib/pgsql/graduationDate_migrate_gradsem_4.sql"
  become_user: postgres
  become: true

- name: run sql commands graduationDate 5
  shell: "psql -U postgres {{ vireo_db4_name[current_site] }} < /var/lib/pgsql/defenseDate_migrate_5.sql"
  become_user: postgres
  become: true

#- name: run sql commands final_add
#  shell: "psql -U postgres {{ vireo_db4_name[current_site] }} < /var/lib/pgsql/final_add.sql"
#  become_user: postgres
#  become: true
#  when: run_sql


- name: run sql commands 428_submission_action_log_column_0.sql
  shell: "psql -U postgres {{ vireo_db4_name[current_site] }} < /var/lib/pgsql/428_submission_action_log_column_0.sql"
  become_user: postgres
  become: true

- name: run sql commands 428_submission_list_column_constraints_1.sql
  shell: "psql -U postgres {{ vireo_db4_name[current_site] }} < /var/lib/pgsql/428_submission_list_column_constraints_1.sql"
  become_user: postgres
  become: true

- name: run sql commands  428_submission_action_log_column_data_2.sql
  shell: "psql -U postgres {{ vireo_db4_name[current_site] }} < /var/lib/pgsql/428_submission_action_log_column_data_2.sql"
  become_user: postgres
  become: true

- name: run sql commands 428_managed_configuration_lowercase_update_3.sql
  shell: "psql -U postgres {{ vireo_db4_name[current_site] }} < /var/lib/pgsql/428_managed_configuration_lowercase_update_3.sql"
  become_user: postgres
  become: true

- name: run sql commands 428_submission_list_column_graduationsemester_list_4.sql
  shell: "psql -U postgres {{ vireo_db4_name[current_site] }} < /var/lib/pgsql/428_submission_list_column_graduationsemester_list_4.sql"
  become_user: postgres
  become: true

- name: run sql commands 428_submission_list_column_submissiontype_list_5.sql
  shell: "psql -U postgres {{ vireo_db4_name[current_site] }} < /var/lib/pgsql/428_submission_list_column_submissiontype_list_5.sql"
  become_user: postgres
  become: true

- name: run sql commands 428_submission_list_column_studentname_6.sql
  shell: "psql -U postgres {{ vireo_db4_name[current_site] }} < /var/lib/pgsql/428_submission_list_column_studentname_6.sql"
  become_user: postgres
  become: true

- name: run sql commands 428_submission_list_column_lastevent_7.sql
  shell: "psql -U postgres {{ vireo_db4_name[current_site] }} < /var/lib/pgsql/428_submission_list_column_lastevent_7.sql"
  become_user: postgres
  become: true



