---
# tasks file for vireo4.server

- name: Start with modified SYSTEM_Organization_Definition.json
  template:
    src: SYSTEM_Organization_Definition_json.j2
    dest: "{{ vireo_codedir }}/etd/Vireo/src/main/resources/organization/SYSTEM_Organization_Definition.json"
    owner: "{{vireo_user}}"
    mode: 0644
  become: yes
  #ignore_errors: yes

- name: Move modified version of SYSTEM_Organization_Definition.json in place (also done in vireo4.server_config)
  copy:
    src: "{{ vireo_codedir }}/etd/SYSTEM_Organization_Definition.json_generated"
    dest: "{{ vireo_codedir }}/etd/Vireo/src/main/resources/organization/SYSTEM_Organization_Definition.json"
    owner: "{{vireo_user}}"
    remote_src: yes
  ignore_errors: yes
  become: yes
  become_user: "{{vireo_user}}"
  when: customize_organization

- name: create application.yml from j2
  template:
    src: "application_yaml_{{ vireo_warversion }}.j2"
    dest: "{{ vireo_codedir }}/etd/Vireo/src/main/resources/application.yml"
    owner: "{{vireo_user}}"
    mode: 0644
  become: yes


#- name: edit pom.xml
#  replace:
#    path: "{{ vireo_codedir }}/etd/Vireo/pom.xml"
#    regexp: 'application.yml'
#    replace: 'application.yaml'
#    owner: "{{vireo_user}}"
#  become: yes

- name: edit pom.xml WW
  replace:
    path: "{{ vireo_codedir }}/etd/Vireo/pom.xml"
    regexp: '<maven.compiler.release>\${java.version}</maven.compiler.release>'
    replace: ' '
    owner: "{{vireo_user}}"
  become: yes

- name: remove extraneous application-test.yml file
  ansible.builtin.file:
    path: "{{ vireo_codedir }}/etd/Vireo/src/main/resources/application-test.yml"
    state: absent
  become: yes

- name: remove node_modules dir
  ansible.builtin.file:
    path: "{{ vireo_codedir }}/etd/Vireo/node_modules/"
    state: absent
  become: yes

- name: build appConfig.js.template from j2 because replace doesn't work on new AWS
  template:
    src: appConfig_js_template_{{ vireo_warversion }}.j2
    dest: "{{ vireo_codedir }}/etd/Vireo/{{ app_config_path }}"
    owner: "{{vireo_user}}"
    mode: 0644
  become: yes


